apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: kyrosbus
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31110
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kyrosbus
  template:
    metadata:
      labels:
        app: kyrosbus
    spec:
      containers:
        - name: kyrosserver
          image: ananddocker18/kyrosbus:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
