kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: nodeweb
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeweb
  template:
    metadata:
      labels:
        app: nodeweb 
    spec:
      containers:
        - name: nodeweb
          image: ananddocker18/kyrosbus:latest
          imagePullPolicy: Always
          ports:
          -name: http 
           containerport: 3000
           protocol: TCP
